[env]
TERM = "alacritty"

[font]
size = 11.0

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Control"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command"

[scrolling]
history = 50000

[window]
dynamic_title = true
opacity = 0.85
title = "Alacritty"
